Update docker readme configuration
For some docker installations, adding the "--insecure-registry" doesn't work.
It's causing the following error:
ERROR: Get https://ci.int.centreon.com:5000/v1/_ping: http: server gave HTTP response to HTTPS client

In this case, the insecure registry needs to be defined in the file /etc/docker/daemon.json file.